node -e "$(cat server.js)" -i &> errorlog2.txt;
sleep 10;
node -e "$(cat server.js)" -i &> errorlog2.txt;
sleep 10;
node -e "$(cat server.js)" -i &> errorlog2.txt;
sleep 10;
node server.js;
sleep 10;
node server.js;
sleep 10;
node server.js;
sleep 10;
node server.js;